apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-openshift
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knative-openshift
  template:
    metadata:
      labels:
        name: knative-openshift
        app: openshift-admission-server
    spec:
      serviceAccountName: knative-openshift
      containers:
        - name: knative-openshift
          image: docker.io/jcrossley3/knative-operator
          command:
          - knative-openshift
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "knative-openshift"
            - name: MIN_OPENSHIFT_VERSION
              value: "4.3.0-0"
            - name: REQUIRED_SERVING_NAMESPACE
              value: "knative-serving"
            - name: REQUIRED_EVENTING_NAMESPACE
              value: "knative-eventing"
            - name: KOURIER_MANIFEST_PATH
              value: deploy/resources/kourier/kourier-latest.yaml
