[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.4"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"
  version = "v1.4.7"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.4"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.4.0"

[[override]]
  name = "k8s.io/utils"
  revision = "581e00157fb1a0435d4fac54a52d1ca1e481d60e"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  version = "=v0.2.2"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.13.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.3.0"

[[constraint]]
  name = "knative.dev/serving"
  branch = "release-0.13"

[[override]]
  name = "knative.dev/pkg"
  branch = "release-0.13"

[prune]
  go-tests = true
  non-go = true
