apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-knative/serverless-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "konflux" && files.all.exists(x, !x.matches('^olm-catalog/'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: serverless-operator-konflux
    appstudio.openshift.io/component: serverless-ingress
    pipelines.appstudio.openshift.io/type: build
  name: serverless-ingress-on-push
  namespace: ocp-serverless-tenant
spec:
  params:
  - name: dockerfile
    value: serving/ingress/Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-serverless-tenant/serverless-operator-konflux/serverless-ingress:{{revision}}
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: serverless-image
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
