---
schema: olm.channel
name: stable
package: serverless-operator
entries:
  - name: "serverless-operator.v1.30.0"
  - name: "serverless-operator.v1.31.0"
    replaces: "serverless-operator.v1.30.0"
    skipRange: ">=1.30.0 <1.31.0"
  - name: "serverless-operator.v1.32.0"
    replaces: "serverless-operator.v1.31.0"
    skipRange: ">=1.31.0 <1.32.0"
---
schema: olm.channel
name: stable-1.32
package: serverless-operator
entries:
  - name: "serverless-operator.v1.30.0"
  - name: "serverless-operator.v1.31.0"
    replaces: "serverless-operator.v1.30.0"
    skipRange: ">=1.30.0 <1.31.0"
  - name: "serverless-operator.v1.32.0"
    replaces: "serverless-operator.v1.31.0"
    skipRange: ">=1.31.0 <1.32.0"
---
schema: olm.channel
name: stable-1.31
package: serverless-operator
entries:
  - name: "serverless-operator.v1.30.0"
  - name: "serverless-operator.v1.31.0"
    replaces: "serverless-operator.v1.30.0"
    skipRange: ">=1.30.0 <1.31.0"
---
schema: olm.channel
name: stable-1.30
package: serverless-operator
entries:
  - name: "serverless-operator.v1.30.0"
